### ISSUE TITLE
[meta] Refactoring

### ISSUE THREAD

**Issue by richardgoater** [PhyloCanvas/PhyloCanvas#105]
- [x] Move loading functions out of `Tree`, remove old `Loader`
- [x] Move parsing functions out of `Tree` and `Branch`
- [x] Move `translateClick` functions from `Tree` to `utils/canvas`
- [x] Don't store renderers on Tree, expose them on the module public API
- [x] Move mutations in `Tree.setNodeColourAndShape` to `Branch`, remove duplicate logic from newick parser
- [x] `drawNode` function is too complicated
- [x] `TreeType` definition objects encapsulating rendering functions
  - [x] Remove concept of `interx`/`intery` from circular tree
  - [x] Standardise calculation of `nodeAlign` extension across branch renderers 
  - [x] Remove `treeType ===` conditional blocks

Proposals:
- [ ] `Node` or `Leaf` class to make `Branch` cleaner

**Comment by richardgoater** [comment]
Final outstanding item covered in #159.
