### ISSUE TITLE
[meta] Backports to 1.x

### ISSUE THREAD

**Issue by richardgoater** [PhyloCanvas/PhyloCanvas#107]
- [x] Relaxed regex for tree parsing
- [x] Firefox on Linux fix
- [x] Normalised zooming
- [x] Updated context menu

**Comment by richardgoater** [comment]
Using `backport` label from now on.
